#Default Config
## Use profile java -jar app.jar -Dspring.profiles.active=<Profile-Name>
application:
  name: Ich bin eine Spring Demo (Application Name)
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  autoconfigure:
      exclude: org.keycloak.adapters.springboot.KeycloakSpringBootConfiguration
  datasource:
    url: jdbc:h2:mem:bestgames;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
logging:
  level:
    root: INFO #DEBUG,INFO,WARN,ERROR
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
# Dev Config
spring:
  profiles: dev

keycloak:
  enabled: false

---
#Cloud Config
spring:
  profiles: keycloak

keycloak:
    auth-server-url: http://keycloak:3000/auth
    public-client: true
    realm: SpringBootKeycloak
    resource: login-app
    security-constraints:
    -   authRoles:
        - user
        securityCollections:
        -   patterns:
            - /games/*
